<?php

namespace OpenContrib\ProjectsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
  public function getProjectsBy3()
  {
    $query = $this->createQueryBuilder('p')
      ->getQuery()
      ->setMaxResults(3)
    ;

    return $query->getResult();
  }
}
